// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1fxGQF6pw2Mk3vj6Q8YWrEl2HAgYdXME',
    appId: '1:942557431731:android:07a60e128a5333511cedc6',
    messagingSenderId: '942557431731',
    projectId: 'hue-to-hue',
    databaseURL: 'https://hue-to-hue-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hue-to-hue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU94CTdNOU-fmmZ1c83sZyjoqcQDO2LoI',
    appId: '1:942557431731:ios:44328aa9fe251ed51cedc6',
    messagingSenderId: '942557431731',
    projectId: 'hue-to-hue',
    databaseURL: 'https://hue-to-hue-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hue-to-hue.appspot.com',
    androidClientId: '942557431731-lun1ggsgt8tc1n4jgjc25plqim3d02io.apps.googleusercontent.com',
    iosClientId: '942557431731-i4ivm6bt99im4t54lp6cjj8gtf55nkt8.apps.googleusercontent.com',
    iosBundleId: 'co.geeksempire.huehue',
  );
}
