name: huehue
description: Hue To Hue; A Game To Improve Your Visions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



  ####### ####### #######
  back_button_interceptor: ^6.0.1

  blobs: ^2.0.0
  blur: ^3.1.0
  ####### ####### #######



  ####### ####### #######
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.0
  ####### ####### #######



  ####### ####### #######
  firebase_core: ^2.24.2
  firebase_app_check: ^0.2.1+8

  firebase_auth: ^4.16.0

  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9

  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10

  firebase_in_app_messaging: ^0.7.0+5

  flutter_app_name: ^0.1.1

  flutter_inner_shadow: 0.0.1

  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.1.6
  ####### ####### #######



  ####### ####### #######
  games_services: ^3.0.0

  google_sign_in: ^5.4.2
  ####### ####### #######



  ####### ####### #######
  just_audio: ^0.9.31
  ####### ####### #######



  ####### ####### #######
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\loading_animation_widget'
  ####### ####### #######



  ####### ####### #######
  path_provider: ^2.0.11
  ####### ####### #######



  ####### ####### #######
  quick_actions: ^0.6.0+11
  ####### ####### #######



  ####### ####### #######
  share_plus: ^4.0.10

  shared_preferences: ^2.0.15

  status_bar_control: ^3.2.1
  ####### ####### #######



  ####### ####### #######
  url_launcher: ^6.1.5
  ####### ####### #######



  ####### ####### #######
  flutter_styled_toast: ^2.1.3
  ####### ####### #######



  ####### ####### #######
  widget_mask: ^1.0.0+0
  ####### ####### #######



  ####### ####### #######
  syncfusion_flutter_core: ^20.4.44
  syncfusion_flutter_sliders: ^20.4.44
  ####### ####### #######



  ####### ####### #######
  vector_math: ^2.0.8
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/back.png
    - assets/blob_bottom.png
    - assets/blob_play.png
    - assets/blob_top.png
    - assets/blob_preferences_bottom.png
    - assets/blob_preferences_top.png
    - assets/blob_previous_top.png
    - assets/blob_previous_bottom.png

    - assets/chaotic_play.png

    - assets/delete_account.png

    - assets/leaderboard.png
    - assets/level_indicator.png
    - assets/level_indicator_bottom.png
    - assets/link.png
    - assets/logo.png
    - assets/logo_background.png
    - assets/logo_android.png
    - assets/logo_ios.png
    - assets/luck_indicator.png

    - assets/point_indicator.png
    - assets/preferences_pointer.png
    - assets/preferences_bottom_pointer.png

    - assets/restart_blob_play.png

    - assets/settings.png
    - assets/squircle.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf
    - family: Nasa
      fonts:
        - asset: fonts/nasa.ttf



flutter_native_splash:
  color: "#120A18"
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    color: "#120A18"

  android: true
  ios: true
  web: false



flutter_icons:
  image_path_android: "assets/logo_android.png"
  image_path_ios: "assets/logo_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/logo_background.png"
  adaptive_icon_foreground: "assets/logo.png"



flutter_app_name:
  name: "Hue To Hue"