name: huehue
description: Hue To Hue; A Game To Improve Your Visions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  ####### ####### #######
  animated_counter: ^1.0.0
  ####### ####### #######



  ####### ####### #######
  back_button_interceptor: ^6.0.1

  blobs: ^2.0.0
  blur: ^3.1.0
  ####### ####### #######



  ####### ####### #######
  cupertino_icons: ^1.0.2
  ####### ####### #######



  ####### ####### #######
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.9
  cloud_firestore: ^4.3.1

  flutter_app_name: ^0.1.1

  flutter_inner_shadow: 0.0.1

  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.1.6
  ####### ####### #######



  ####### ####### #######
  just_audio: ^0.9.31
  ####### ####### #######



  ####### ####### #######
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\SachielProject\loading_animation_widget'
  ####### ####### #######



  ####### ####### #######
  quick_actions: ^0.6.0+11
  ####### ####### #######



  ####### ####### #######
  share_plus: ^4.0.10

  shared_preferences: ^2.0.15

  status_bar_control: ^3.2.1
  ####### ####### #######



  ####### ####### #######
  url_launcher: ^6.1.5
  ####### ####### #######



  ####### ####### #######
  widget_mask: ^1.0.0+0
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - back.png
    - blob_bottom.png
    - blob_play.png
    - blob_top.png
    - blob_preferences_bottom.png
    - blob_preferences_top.png

    - chaotic.png

    - level_indicator.png
    - level_indicator_bottom.png
    - link.png
    - logo.png
    - logo_background.png
    - logo_android.png
    - logo_ios.png
    - point_indicator.png

    - preferences_pointer.png

    - settings.png
    - squircle.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf
    - family: Nasa
      fonts:
        - asset: fonts/nasa.ttf



flutter_native_splash:
  color: "#120A18"
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    color: "#120A18"

  android: true
  ios: true
  web: false



flutter_icons:
  image_path_android: "assets/logo_android.png"
  image_path_ios: "assets/logo_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/logo_background.png"
  adaptive_icon_foreground: "assets/logo.png"



flutter_app_name:
  name: "Hue To Hue"