name: huehue
description: Hue To Hue; A Game To Improve Your Visions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



  ####### ####### #######
  app_version_update: ^4.0.1
  ####### ####### #######



  ####### ####### #######
  back_button_interceptor: ^7.0.2

  blobs: ^2.0.0
  blur: ^3.1.0
  ####### ####### #######



  ####### ####### #######
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.8
  ####### ####### #######



  ####### ####### #######
  firebase_core: ^2.27.0
  firebase_app_check: ^0.2.1+17

  firebase_auth: ^4.17.8

  firebase_analytics: ^10.8.9
  firebase_crashlytics: ^3.4.18

  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19

  firebase_in_app_messaging: ^0.7.4+17

  flutter_inner_shadow: 0.0.1
  ####### ####### #######



  ####### ####### #######
  games_services:
    path: 'X:\Xlutter\Libraries\games_services'

  google_sign_in: ^6.2.1
  ####### ####### #######



  ####### ####### #######
  just_audio: ^0.9.36
  ####### ####### #######



  ####### ####### #######
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\loading_animation_widget'
  ####### ####### #######



  ####### ####### #######
  path_provider: ^2.1.2
  ####### ####### #######



  ####### ####### #######
  quick_actions: ^1.0.7
  ####### ####### #######



  ####### ####### #######
  share_plus: ^7.2.2

  shared_preferences: ^2.2.2

  status_bar_control:
    path: 'X:\Xlutter\Libraries\flutter_statusbar_control'
  ####### ####### #######



  ####### ####### #######
  url_launcher: ^6.2.5
  ####### ####### #######



  ####### ####### #######
  flutter_styled_toast: ^2.2.1
  ####### ####### #######



  ####### ####### #######
  widget_mask: ^1.0.0+0
  ####### ####### #######



  ####### ####### #######
  ####### ####### #######



  ####### ####### #######
  vector_math: ^2.1.4
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf
    - family: Nasa
      fonts:
        - asset: fonts/nasa.ttf